services:
  - type: web
    name: flask-hello-world
    env: python
    plan: free  # or 'starter', 'standard', etc., depending on your needs
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    autoDeploy: true  # Automatically deploy when new changes are pushed
